// Featured recipes for the recipes page
// 16 recipes from 8 diet plans with images
// Auto-generated by scripts/update-featured-recipes.js

export const featuredRecipes = [
  {
    "id": "1a8125dd-4f0b-42a2-bc0d-8e4139a3096b",
    "name": "Pumpkin Pie Overnight Oats",
    "description": "A delicious and nutritious breakfast that tastes like pumpkin pie! Kids will love the creamy texture and familiar flavors.",
    "prep_time": 10,
    "cook_time": 0,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/1a8125dd-4f0b-42a2-bc0d-8e4139a3096b/pumpkin-pie-overnight-oats-1760501591377.png",
    "diet_plan_names": [
      {
        "name": "Family Focused",
        "slug": "family-focused"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 12,
        "carbs": 45,
        "fiber": 6,
        "protein": 10,
        "calories": 320
      }
    ]
  },
  {
    "id": "7e3845f9-cb12-4927-a716-9aefd10ddb99",
    "name": "Baked Chicken Tenders with Roasted Veggies",
    "description": "Crispy, golden chicken tenders paired with colorful roasted veggies - a delicious and nutritious lunch the whole family will love!",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/7e3845f9-cb12-4927-a716-9aefd10ddb99/baked-chicken-tenders-with-roasted-veggies-1760501599144.png",
    "diet_plan_names": [
      {
        "name": "Family Focused",
        "slug": "family-focused"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 15,
        "carbs": 30,
        "fiber": 8,
        "protein": 25,
        "calories": 350
      }
    ]
  },
  {
    "id": "5bd6e06f-9b80-44bb-91f5-33c596565484",
    "name": "Moroccan Chicken Tagine with Couscous",
    "description": "A fragrant and flavorful Moroccan dish featuring tender chicken, aromatic spices, and fluffy couscous. This authentic recipe transports you to the vibrant markets of Marrakech.",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/5bd6e06f-9b80-44bb-91f5-33c596565484/moroccan-chicken-tagine-with-couscous-1760555399070.png",
    "diet_plan_names": [
      {
        "name": "Global Cuisine",
        "slug": "global-cuisine"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 15,
        "carbs": 45,
        "fiber": 6,
        "protein": 25,
        "calories": 415
      }
    ]
  },
  {
    "id": "7aa525a4-8a7d-4738-838c-7ff851f78b81",
    "name": "Moroccan Chickpea and Vegetable Tagine",
    "description": "A fragrant and flavorful Moroccan-inspired tagine featuring chickpeas, seasonal vegetables, and aromatic spices. Served over fluffy couscous, this dish showcases the vibrant tastes of North Africa.",
    "prep_time": 20,
    "cook_time": 30,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/7aa525a4-8a7d-4738-838c-7ff851f78b81/moroccan-chickpea-and-vegetable-tagine-1760555406101.png",
    "diet_plan_names": [
      {
        "name": "Global Cuisine",
        "slug": "global-cuisine"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 30,
        "carbs": 45,
        "fiber": 8,
        "protein": 25,
        "calories": 350
      }
    ]
  },
  {
    "id": "77108302-73d9-4864-a34b-0384da4987f7",
    "name": "Autumn Spiced Protein Oatmeal",
    "description": "Warm and comforting oatmeal packed with protein, healthy fats, and fall flavors to keep you full and energized during your Intermittent Fasting Eating Window.",
    "prep_time": 10,
    "cook_time": 10,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/77108302-73d9-4864-a34b-0384da4987f7/autumn-spiced-protein-oatmeal-1760501909769.png",
    "diet_plan_names": [
      {
        "name": "Intermittent Fasting",
        "slug": "intermittent-fasting"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 18,
        "carbs": 30,
        "fiber": 8,
        "protein": 12,
        "calories": 340
      }
    ]
  },
  {
    "id": "f6a30ace-38e2-4d94-96e0-f3625c149f48",
    "name": "Protein-Packed Autumn Harvest Salad",
    "description": "This nutrient-dense, high-satiety salad is perfect for breaking your intermittent fasting window. Featuring roasted fall veggies, lean turkey, and healthy fats, it will keep you full for hours.",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/f6a30ace-38e2-4d94-96e0-f3625c149f48/protein-packed-autumn-harvest-salad-1760501917017.png",
    "diet_plan_names": [
      {
        "name": "Intermittent Fasting",
        "slug": "intermittent-fasting"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 15,
        "carbs": 30,
        "fiber": 10,
        "protein": 30,
        "calories": 350
      }
    ]
  },
  {
    "id": "f3f0c826-fb9b-4aa1-a594-e0ff235b3c53",
    "name": "Baked Avocado Eggs",
    "description": "A delicious and satisfying keto-friendly breakfast that combines creamy avocado with baked eggs for a nutrient-dense meal.",
    "prep_time": 15,
    "cook_time": 15,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/f3f0c826-fb9b-4aa1-a594-e0ff235b3c53/baked-avocado-eggs-1760032381982.png",
    "diet_plan_names": [
      {
        "name": "Keto Diet",
        "slug": "keto"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 38,
        "carbs": 5,
        "fiber": 8,
        "protein": 20,
        "calories": 425
      }
    ]
  },
  {
    "id": "3ff90480-31ac-40b5-bb85-6e402ceeac15",
    "name": "Baked Pumpkin Spice Frittata",
    "description": "A delicious and nutrient-dense keto breakfast featuring fall flavors of pumpkin and spice.",
    "prep_time": 15,
    "cook_time": 30,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/3ff90480-31ac-40b5-bb85-6e402ceeac15/baked-pumpkin-spice-frittata-1760033640907.png",
    "diet_plan_names": [
      {
        "name": "Keto Diet",
        "slug": "keto"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 25,
        "carbs": 5,
        "fiber": 2,
        "protein": 20,
        "calories": 320
      }
    ]
  },
  {
    "id": "6a402e05-2612-4bae-9142-430314baeaad",
    "name": "Mediterranean Quinoa Breakfast Bowl",
    "description": "A nourishing and flavorful breakfast bowl featuring quinoa, roasted vegetables, and a Mediterranean-inspired dressing.",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/6a402e05-2612-4bae-9142-430314baeaad/mediterranean-quinoa-breakfast-bowl-1760032592283.png",
    "diet_plan_names": [
      {
        "name": "Mediterranean Diet",
        "slug": "mediterranean"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 13,
        "carbs": 45,
        "fiber": 6,
        "protein": 10,
        "calories": 320
      }
    ]
  },
  {
    "id": "e372d12a-3747-4d66-9148-5b37b38f9565",
    "name": "Mediterranean Baked Egg Cups",
    "description": "A delicious and nutritious Mediterranean-inspired breakfast featuring baked eggs with vegetables, whole grains, and healthy fats.",
    "prep_time": 15,
    "cook_time": 20,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/e372d12a-3747-4d66-9148-5b37b38f9565/mediterranean-baked-egg-cups-1760032599018.png",
    "diet_plan_names": [
      {
        "name": "Mediterranean Diet",
        "slug": "mediterranean"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 15,
        "carbs": 30,
        "fiber": 5,
        "protein": 20,
        "calories": 350
      }
    ]
  },
  {
    "id": "624cd3fd-9e78-4d4b-9e69-c74dfc16783c",
    "name": "Paleo Baked Salmon and Roasted Veggies",
    "description": "A delicious and nutritious paleo-friendly breakfast featuring baked salmon, roasted winter vegetables, and a touch of lemon and herbs.",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "difficulty": "easy",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/624cd3fd-9e78-4d4b-9e69-c74dfc16783c/paleo-baked-salmon-and-roasted-veggies-1760131543679.png",
    "diet_plan_names": [
      {
        "name": "Paleo",
        "slug": "paleo"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 15,
        "carbs": 35,
        "fiber": 8,
        "protein": 30,
        "calories": 350
      }
    ]
  },
  {
    "id": "f7c8a0cd-00b3-449f-b304-5e5ed4a48a11",
    "name": "Roasted Salmon with Baked Sweet Potatoes and Sautéed Kale",
    "description": "A delicious and nutritious paleo-friendly dinner featuring tender roasted salmon, baked sweet potatoes, and sautéed kale.",
    "prep_time": 15,
    "cook_time": 30,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/f7c8a0cd-00b3-449f-b304-5e5ed4a48a11/roasted-salmon-with-baked-sweet-potatoes-and-saut-ed-kale-1760131565287.png",
    "diet_plan_names": [
      {
        "name": "Paleo",
        "slug": "paleo"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 15,
        "carbs": 35,
        "fiber": 7,
        "protein": 30,
        "calories": 380
      }
    ]
  },
  {
    "id": "48e9ad99-32f8-46d5-b98e-67343ff7f882",
    "name": "Winter Lentil and Quinoa Stew",
    "description": "A hearty and nourishing vegan stew featuring plant-based proteins, seasonal vegetables, and whole grains.",
    "prep_time": 15,
    "cook_time": 30,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/48e9ad99-32f8-46d5-b98e-67343ff7f882/winter-lentil-and-quinoa-stew-1760132768563.png",
    "diet_plan_names": [
      {
        "name": "Vegan",
        "slug": "vegan"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 30,
        "carbs": 55,
        "fiber": 10,
        "protein": 15,
        "calories": 350
      }
    ]
  },
  {
    "id": "846d8c50-66c7-4129-8ab7-f4f7f796252f",
    "name": "Winter Vegetable and Quinoa Stir-Fry",
    "description": "A hearty and flavorful vegan lunch packed with plant-based proteins, seasonal vegetables, and whole grains.",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/846d8c50-66c7-4129-8ab7-f4f7f796252f/winter-vegetable-and-quinoa-stir-fry-1760132818249.png",
    "diet_plan_names": [
      {
        "name": "Vegan",
        "slug": "vegan"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 30,
        "carbs": 55,
        "fiber": 9,
        "protein": 15,
        "calories": 345
      }
    ]
  },
  {
    "id": "e3f64a3c-0b9a-44f8-810a-d6090e9e36e5",
    "name": "Autumn Harvest Vegetable Stir-Fry",
    "description": "A delicious and nutritious vegetarian stir-fry featuring seasonal fall produce, grains, and a creamy dairy-based sauce.",
    "prep_time": 20,
    "cook_time": 20,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/e3f64a3c-0b9a-44f8-810a-d6090e9e36e5/autumn-harvest-vegetable-stir-fry-1760132372607.png",
    "diet_plan_names": [
      {
        "name": "Vegetarian",
        "slug": "vegetarian"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 30,
        "carbs": 50,
        "fiber": 8,
        "protein": 20,
        "calories": 350
      }
    ]
  },
  {
    "id": "61a2da03-c29e-4add-95f9-7639944048e9",
    "name": "Autumn Vegetable Quinoa Salad",
    "description": "A hearty and flavorful vegetarian lunch that celebrates the bounty of fall produce.",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "difficulty": "medium",
    "image_url": "https://rnvowqoqqcrimrybuiea.supabase.co/storage/v1/object/public/recipe-images/recipes/61a2da03-c29e-4add-95f9-7639944048e9/autumn-vegetable-quinoa-salad-1760132400763.png",
    "diet_plan_names": [
      {
        "name": "Vegetarian",
        "slug": "vegetarian"
      }
    ],
    "recipe_nutrition": [
      {
        "fat": 30,
        "carbs": 50,
        "fiber": 8,
        "protein": 20,
        "calories": 350
      }
    ]
  }
]
